### ISSUE TITLE
post invitation redirect is not happening

### ISSUE THREAD

**Issue by svevang** [michaelkirk/weiqi#29]
After claiming an invitation the black player should be redirected to `/boards/<black_player_id>`. This is currently not happening.

**Comment by svevang** [comment]
hmm, I'm not able to reproduce this atm, closing this for now and am off to reboot chrome ;P

**Comment by michaelkirk** [comment]
When I click on start a game
And  click on "copy this URL"
Then I am taken to http://go.jackpine.me/boards/go.jackpine.me/invitations/0ca2298e25d9d276d73f78a3
But I should be taken to http://go.jackpine.me/invitations/0ca2298e25d9d276d73f78a3
